@rootURL = https://localhost:7190


GET {{rootURL}}/weatherforecast/
Accept: application/json

###
GET {{rootURL}}/api/book
Accept: application/json

### Obtenir un livre par ID
GET {{rootURL}}/api/book/2
Accept: application/json

###
POST {{rootURL}}/api/book
Content-Type: application/json

{
  "id": 6,
  "title": "C# unlock",
  "author": "Alen",
  "yearPublished": 2025
}

###
PUT {{rootURL}}/api/book/5
Content-Type: application/json

{
  "id": 5,
  "title": "C# unlock",
  "author": "Alen",
  "yearPublished": 2025
}
